getwd()
hsm <- read.table("output/aggregate.txt", sep=",", header=TRUE, strip.white = TRUE)
table(hsm$misses)
sum(hsm$hits) / sum(hsm$shots)
str(subset(hsm, complete > 6))
library(ggplot2)
dir.create("output", showWarnings = FALSE)
pdf(file = "output/byhover.pdf")
ggplot(hsm, aes(complete, fill=as.factor(hovers))) + geom_histogram(pos="dodge")
dev.off()
pdf(file = "output/bywhiff.pdf")
ggplot(hsm, aes(complete, fill=as.factor(whiffs))) + geom_histogram(pos="dodge")
dev.off()
pdf(file = "output/bymiss.pdf")
ggplot(hsm, aes(complete, fill=as.factor(misses))) + geom_histogram(pos="dodge")
dev.off()
pdf(file = "output/byavoid.pdf")
ggplot(hsm, aes(complete, fill=as.factor(avoids))) + geom_histogram(pos="dodge")
dev.off()
pdf(file = "output/byorder.pdf")
ggplot(hsm, aes(complete, fill=as.factor(order))) + geom_histogram(pos="dodge")
dev.off()
